version: "2.3"

services:

  app:
    image: exadra37/hangman:${RELEASE_TAG:-latest}
    build:
      context: .
      args:
        ALPINE_VERSION: "${ALPINE_VERSION:-3.20.3}"
        ELIXIR_VERSION: "${ELIXIR_VERSION:-1.13.3}"
        OTP_VERSION: "${ERLANG_OTP_VERSION:-24.3.3}"
        BUILD_RELEASE_FROM: "${BUILD_RELEASE_FROM:-main}"

    restart: unless-stopped
    env_file:
      - .env
    networks:
      - traefik
      - default
    ports:
          - 127.0.0.1:${PUBLIC_DOMAIN_PORT}:${SERVER_HTTP_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${PUBLIC_DOMAIN? Missing env var PUBLIC_DOMAIN}"
      - "traefik.docker.network=traefik"
      - "traefik.port=${SERVER_HTTP_PORT}"
      - "traefik.frontend.rule=Host:${PUBLIC_DOMAIN}"

networks:
  traefik:
    external: true
